[package]
name = "lvbitfile2rust-cli"
version = "0.1.0"
authors = ["Connor Worley <cworley@dropbox.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lvbitfile2rust = { path = "../lvbitfile2rust" }
